services:
  - type: web
    name: MDM-BRASIL
    env: python
    plan: free
    region: oregon
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn server.main:app --host 0.0.0.0 --port 10000"
